### PR TITLE
Update linux video support

### PR DESCRIPTION
**Pull request by g-bougard**
To replace #217 & #218

### CODE REVIEW

**Comment by g-bougard** [comment]
Hi @biji,

can you test this PR ?

It follows your requirement from #217 & #218 but guarantee to not duplicate video because of current linux video support. Indeed, this PR also deprecates the current linux video support based of log file parsing and this module will only be used if nothing is found using lspci.

To better support nvidia cards I added a specific module which finds the right memory size and may update resolution, chipset or card name. Maybe you can add one for your own manufacturer if you need it and find how to do.

**Comment by biji** [comment]
The memory on second row is invalid:

```
      "videos": [
         {
            "chipset": "Intel Corporation TigerLake-LP GT2",
            "memory": 256,
            "name": "ASUSTeK Computer Inc. Iris Xe Graphics",
            "pcislot": "0000:00:02.0"
         },
         {
            "chipset": "NVIDIA Corporation TU117M",
            "memory": 288,
            "name": "ASUSTeK Computer Inc. GeForce GTX 1650 Mobile / Max-Q",
            "pcislot": "0000:01:00.0"
         },
         {
            "chipset": "NVIDIA Corporation TU117M",
            "memory": 4096,
            "name": "NVIDIA Corporation GeForce GTX 1650 Mobile / Max-Q",
            "pcislot": "01:00.0"
         }
      ]

```

**Comment by g-bougard** [comment]
Indeed...
And indeed, the third entry should have been an update for the second. But it seems the "pcislot" is not formatted the same way. I should better parse the pciclot to compare them and decide to update an entry.

**Comment by g-bougard** [comment]
Hi @biji 
can you share for this computer the output of:
```
lspci -v -nn
```
I would like to understand why we have a prefix "0000:" on the pcislot numbering.

And can you also share the output of:
```
nvidia-settings -t -c all -q gpus
```
and
```
nvidia-settings -t -c :0 -q all
```

**Comment by biji** [comment]
here you go,
https://gist.github.com/biji/282ab1530bbf932bad3cefbbadec26ef

`0000:`  probably because of kernel version 5.19

**Comment by g-bougard** [comment]
Thank you @biji 
this really helped.
Indeed, it seems you have another PCI controller dedicated to nvme support and this creates a new PCI "domain". I've myself a 5.19 kernel and lspci doesn't show the PCI domain. It should only show it if more than one PCI controller is found.
I also used your sample output to create tests to be sure your case will always be supported.
Can you test this update ?

**Comment by biji** [comment]
great 👍

```
      "versionclient": "GLPI-Inventory_v1.5-dev",
      "videos": [
         {
            "chipset": "Intel Corporation TigerLake-LP GT2",
            "memory": 256,
            "name": "ASUSTeK Computer Inc. Iris Xe Graphics",
            "pcislot": "0000:00:02.0"
         },
         {
            "chipset": "NVIDIA Corporation TU117M",
            "memory": 4096,
            "name": "ASUSTeK Computer Inc. GeForce GTX 1650 Mobile / Max-Q",
            "pcislot": "0000:01:00.0"
         }
      ]
```

**Pull request merged**
