### PR TITLE
Force10 S-series MibSupport

### PR DESCRIPTION
**Pull request by po1vo**
The module itself works, however the data provided messes up Glpi:
Force10 has interface names like `Gi0/1`, where `0` is the stack member (aka chassis) number minus 1. At the same time Glpi takes chassis number from the interface name and expects it to be `> 0`. See the xml below:

```xml
      <COMPONENTS>
        <COMPONENT>
          <CONTAINEDININDEX>0</CONTAINEDININDEX>
          <INDEX>-1</INDEX>
          <NAME>Force10 S-series Stack</NAME>
          <TYPE>stack</TYPE>
        </COMPONENT>
        <COMPONENT>
          <CONTAINEDININDEX>-1</CONTAINEDININDEX>
          <DESCRIPTION>48-port E/FE/GE (SB)</DESCRIPTION>
          <FIRMWARE>8.4.2.7</FIRMWARE>
          <INDEX>1</INDEX>
          <MODEL>S50-01-GE-48T-AC</MODEL>
          <REVISION>D</REVISION>
          <SERIAL>DL250170022</SERIAL>
          <TYPE>chassis</TYPE>
        </COMPONENT>
        <COMPONENT>
          <CONTAINEDININDEX>1</CONTAINEDININDEX>
          <INDEX>34128898</INDEX>
          <TYPE>port</TYPE>
        </COMPONENT>
      </COMPONENTS>
      <PORTS>
        <PORT>
          <IFNAME>GigabitEthernet 0/1</IFNAME>
          <IFNUMBER>34128898</IFNUMBER>
        </PORT>
      <PORTS>
```

P.S. I didn't write tests as there is no test infrastructure for MibSupport (?)

### CODE REVIEW

**Comment by g-bougard** [comment]
Hi @po1vo 
thank you for this submission.

I'm okay with the PR.

If you want to add test, you still can add a walk sample in resources/walks and add a test in a new dedicated folder like t/tasks/netinventory/mibsupport. You can re-use some code from t/tasks/netinventory.t to check the expected result.
But anyway, as the walk would probably contains sensible datas, you can submit it to me privately so I can include it in our private snmp walks repository. I'm using this private repo to check for any regression on netdiscovery/netinventory code.

**Comment by po1vo** [comment]
I've added a test, however i'd hold off adding this code to the main branch. The bug in Glpi created 8 identical switches from a single inventory, where each switch had all ports from the whole stack assigned to it. In other words each one of 8 switches had 384 ports, and those ports were identical between the switches: same MAC, ifindex, etc.

**Comment by g-bougard** [comment]
About the test, can I suggest you to better check getComponents() API results as this is what will be really injected in the inventory and you are adding a last component there in the list ?
I'm okay to hold this PR until the problem is clarified on GLPI side.

**Comment by po1vo** [comment]
Done.

**Review by g-bougard — APPROVED** [review]
Let me know when you want to have it merged.

**Comment by po1vo** [comment]
I think it's ok to merge.

**Comment by g-bougard** [comment]
Hi @po1vo 
just for your information, I pushed ef4d51d4559dcd9580b3b95267c108754c899822 to fix a minor issue detected with our internal automatic tests on our private walks repository.
An error was triggered when we scan a Force10 device without any component detected.

**Pull request merged**
